ALTER TABLE recipe.menu_snapshot_items
    ADD COLUMN IF NOT EXISTS cost_minor BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS low_confidence BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE recipe.menu_snapshot_modifiers
    ADD COLUMN IF NOT EXISTS cost_minor BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS low_confidence BOOLEAN NOT NULL DEFAULT FALSE;
